---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: document
    path: content/about.md
    label: À Propos
  - type: document
    path: content/pain.md
    label: Pains
  - type: document
    path: content/vente.md
    label: Points de vente
  - type: document
    path: content/infos.md
    label: Infos/Contact
upload_dir: public
public_path: "/public"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "."
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
